# Generated by Django 5.2 on 2025-05-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮件')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('product', models.CharField(choices=[('real', '经典款可口可乐'), ('fanda', '雪碧系列'), ('cococola', '芬达系列')], max_length=20, verbose_name='感兴趣的产品')),
                ('quantity', models.IntegerField(default=1, verbose_name='购买数量')),
                ('message', models.TextField(blank=True, verbose_name='留言')),
                ('date_submitted', models.DateTimeField(auto_now_add=True, verbose_name='提交日期')),
            ],
            options={
                'verbose_name': '联系表单',
                'verbose_name_plural': '联系表单',
                'ordering': ['-date_submitted'],
            },
        ),
    ]
